import type { MetricMetadata } from '@/models/schema';

/**
 * Comprehensive metric definitions for the Monetary Shock Monitor
 * Used for tooltips, documentation, and validation
 */
export const METRIC_DEFINITIONS: Record<string, MetricMetadata> = {
  policy_rate_target: {
    metric_id: 'policy_rate_target',
    label: 'Policy Rate Target',
    description: 'Central bank target policy interest rate (Federal Funds Rate equivalent)',
    unit: 'percent',
    source_type: 'Synthetic',
    expected_range: { min: 0, max: 6 },
  },
  policy_rate_change_3m: {
    metric_id: 'policy_rate_change_3m',
    label: 'Policy Rate Change (3M)',
    description: 'Change in policy rate over past 3 months',
    unit: 'basis points',
    source_type: 'Synthetic',
    expected_range: { min: -300, max: 300 },
  },
  yield_2y: {
    metric_id: 'yield_2y',
    label: '2-Year Treasury Yield',
    description: '2-year government bond yield',
    unit: 'percent',
    source_type: 'Synthetic',
    expected_range: { min: 0, max: 6 },
  },
  yield_10y: {
    metric_id: 'yield_10y',
    label: '10-Year Treasury Yield',
    description: '10-year government bond yield',
    unit: 'percent',
    source_type: 'Synthetic',
    expected_range: { min: 0, max: 6 },
  },
  curve_slope_10y_2y: {
    metric_id: 'curve_slope_10y_2y',
    label: 'Yield Curve Slope (10Y-2Y)',
    description: 'Difference between 10-year and 2-year yields. Negative values indicate inversion.',
    unit: 'basis points',
    source_type: 'Synthetic',
    expected_range: { min: -100, max: 200 },
  },
  curve_inversion_flag: {
    metric_id: 'curve_inversion_flag',
    label: 'Yield Curve Inversion Flag',
    description: 'Binary indicator of yield curve inversion (1 = inverted, 0 = normal)',
    unit: 'binary',
    source_type: 'Synthetic',
    expected_range: { min: 0, max: 1 },
  },
  inflation_yoy: {
    metric_id: 'inflation_yoy',
    label: 'Inflation Year-over-Year',
    description: 'Consumer price inflation rate over past 12 months',
    unit: 'percent',
    source_type: 'Synthetic',
    expected_range: { min: -1, max: 8 },
  },
  real_policy_rate: {
    metric_id: 'real_policy_rate',
    label: 'Real Policy Rate',
    description: 'Policy rate adjusted for inflation (nominal rate minus inflation)',
    unit: 'percent',
    source_type: 'Synthetic',
    expected_range: { min: -5, max: 5 },
  },
  money_growth_yoy: {
    metric_id: 'money_growth_yoy',
    label: 'Money Supply Growth YoY',
    description: 'Year-over-year growth rate of broad money supply',
    unit: 'percent',
    source_type: 'Synthetic',
    expected_range: { min: -5, max: 20 },
  },
  central_bank_balance_sheet_index: {
    metric_id: 'central_bank_balance_sheet_index',
    label: 'Central Bank Balance Sheet Index',
    description: 'Index of central bank total assets (baseline = 100)',
    unit: 'index',
    source_type: 'Synthetic',
    expected_range: { min: 80, max: 200 },
  },
  liquidity_stress_index: {
    metric_id: 'liquidity_stress_index',
    label: 'Liquidity Stress Index',
    description: 'Composite measure of market liquidity stress (0 = low stress, 100 = high stress)',
    unit: 'index',
    source_type: 'Synthetic',
    expected_range: { min: 0, max: 100 },
  },
  ig_credit_spread: {
    metric_id: 'ig_credit_spread',
    label: 'Investment Grade Credit Spread',
    description: 'Spread of investment-grade corporate bonds over government bonds',
    unit: 'basis points',
    source_type: 'Synthetic',
    expected_range: { min: 50, max: 300 },
  },
  hy_credit_spread: {
    metric_id: 'hy_credit_spread',
    label: 'High Yield Credit Spread',
    description: 'Spread of high-yield (junk) corporate bonds over government bonds',
    unit: 'basis points',
    source_type: 'Synthetic',
    expected_range: { min: 200, max: 1000 },
  },
  funding_stress_proxy: {
    metric_id: 'funding_stress_proxy',
    label: 'Funding Stress Proxy',
    description: 'Indicator of short-term funding market stress',
    unit: 'basis points',
    source_type: 'Synthetic',
    expected_range: { min: 5, max: 150 },
  },
  volatility_index_proxy: {
    metric_id: 'volatility_index_proxy',
    label: 'Volatility Index Proxy',
    description: 'Market volatility index (VIX-equivalent)',
    unit: 'index',
    source_type: 'Synthetic',
    expected_range: { min: 10, max: 80 },
  },
  risk_off_composite: {
    metric_id: 'risk_off_composite',
    label: 'Risk-Off Composite Index',
    description: 'Composite measure of risk aversion across markets (0 = risk-on, 100 = extreme risk-off)',
    unit: 'index',
    source_type: 'Synthetic',
    expected_range: { min: 0, max: 100 },
  },
};
